#!/usr/bin/env python3
"""
HAProxy Configuration Generator

This script reads an application YAML configuration and generates
the corresponding HAProxy configuration snippet for validation.

Usage:
    python generate-haproxy-config.py <app-config.yml>

Output:
    Prints HAProxy configuration to stdout

Exit codes:
    0 - Generation successful
    1 - Generation failed
"""

import sys
import yaml


def generate_haproxy_config(config: dict) -> str:
    """Generate HAProxy configuration from application config."""
    if 'haproxy' not in config:
        raise ValueError("No HAProxy configuration found in application config")
    
    haproxy = config['haproxy']
    metadata = config.get('metadata', {})
    
    frontend = haproxy.get('frontend', {})
    backend = haproxy.get('backend', {})
    
    lines = []
    
    # Header comment
    lines.append(f"# HAProxy Configuration for: {metadata.get('name', 'unknown')}")
    lines.append(f"# Owner: {metadata.get('owner', 'unknown')}")
    lines.append(f"# Environment: {metadata.get('environment', 'unknown')}")
    lines.append("# Generated by generate-haproxy-config.py")
    lines.append("")
    
    # Frontend configuration
    lines.append(f"frontend {frontend.get('name', 'default-frontend')}")
    lines.append(f"    bind *:{frontend.get('bind_port', 80)}")
    lines.append(f"    mode {frontend.get('mode', 'http')}")
    lines.append("")
    
    # ACL configuration
    if 'acl' in frontend:
        acl = frontend['acl']
        lines.append(f"    # ACL for hostname matching")
        lines.append(f"    acl {acl.get('name', 'default_acl')} {acl.get('match', '')}")
        lines.append(f"    use_backend {backend.get('name', 'default-backend')} if {acl.get('name', 'default_acl')}")
    lines.append("")
    
    # Backend configuration
    lines.append(f"backend {backend.get('name', 'default-backend')}")
    lines.append(f"    mode {backend.get('mode', 'http')}")
    lines.append(f"    balance {backend.get('balance', 'roundrobin')}")
    lines.append("")
    
    # Health check configuration
    health_check = backend.get('health_check', {})
    if health_check.get('enabled', False):
        lines.append("    # Health check configuration")
        lines.append(f"    option httpchk GET {health_check.get('path', '/')}")
        lines.append("    http-check expect status 200")
        lines.append("")
    
    # Backend servers
    lines.append("    # Backend servers")
    for server in backend.get('servers', []):
        server_line = f"    server {server.get('name', 'server')} {server.get('address', '127.0.0.1')}:{server.get('port', 80)}"
        if server.get('options'):
            server_line += f" {server['options']}"
        if health_check.get('enabled', False):
            interval = health_check.get('interval', 5000)
            server_line += f" inter {interval} fall 3 rise 2"
        lines.append(server_line)
    
    return '\n'.join(lines)


def main():
    """Main entry point for the generator."""
    if len(sys.argv) != 2:
        print("Usage: python generate-haproxy-config.py <app-config.yml>", file=sys.stderr)
        sys.exit(1)
    
    config_file = sys.argv[1]
    
    try:
        with open(config_file, 'r') as f:
            config = yaml.safe_load(f)
    except FileNotFoundError:
        print(f"Error: Configuration file not found: {config_file}", file=sys.stderr)
        sys.exit(1)
    except yaml.YAMLError as e:
        print(f"Error: Invalid YAML syntax: {e}", file=sys.stderr)
        sys.exit(1)
    
    if config is None:
        print("Error: Configuration file is empty", file=sys.stderr)
        sys.exit(1)
    
    try:
        haproxy_config = generate_haproxy_config(config)
        print(haproxy_config)
        print("\n# Configuration generated successfully", file=sys.stderr)
        sys.exit(0)
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()
